/*
    +-----+
    | BFC |
    +-----+

    Code-formatting Brainfuck compiler and transpiler with codegen support for C and Linux x86_64 NASM
*/

#include <stdio.h>
#include <errno.h>
#include <string.h>
#include <stdbool.h>
#include <stdlib.h>

enum target {
  TGT_C    = (0 << 1) | 1,
  TGT_NASM = (1 << 1) | 0
};

int main(int argc, char **argv) {
  /* file streams */
  FILE *in = stdin, *out = stdout;
  /* compilation variables */
  int ch, count, indent, orig;
  /* nasm loop stack */
  int loopstack[1024];
  int looptop = 0, loopnext = 0, id;
  /* arg parsing variables */
  int i, j;
  char *arg, *output, *end;
  /* options */
  bool optimise = false, debug = false;
  int memsize = 65536, indsize = 2;
  char *input = NULL;
  enum target target = TGT_C;

  for(i = 1; i < argc; i++) {
    arg = argv[i];
    if(strcmp(arg, "--") == 0) {
      i++;
      break;
    }
    if(arg[0] != '-' || arg[1] == '\0') {
      input = arg;
      i++;
      break;
    }
    for(j = 1; arg[j]; j++) {
      switch(arg[j]) {
        case 'h':
          printf("bfc: brainfuck compiler\n\nusage: %s [options] [--] [infile]\n"
                 "\n"
                 "options:\n"
                 "  -h            show this help message\n"
                 "  -t <c|nasm>   change output language\n"
                 "  -O            enable optimisations\n"
                 "  -d            enable debug mode\n"
                 "  -o <file>     set output filename\n"
                 "  -m <memsize>  set memory tape size\n"
                 "  -i <indsize>  set indentation length\n"
          , argv[0]);
          return 0;
        case 't':
          if(arg[j + 1]) output = &arg[j + 1];
          else if(++i < argc) output = argv[i];
          else {
            fprintf(stderr, "flag 't' requires an argument\n");
            return 1;
          }
          j = strlen(arg) - 1;

          if(strcmp(output, "c") == 0) target = TGT_C;
          else if(strcmp(output, "nasm") == 0) target = TGT_NASM;
          else {
            fprintf(stderr, "invalid target: '%s'\n", output);
            return 1;
          }
          break;
        case 'O':
          optimise = true;
          break;
        case 'd':
          debug = true;
          break;
        case 'o':
          if(arg[j + 1]) output = &arg[j + 1];
          else if(++i < argc) output = argv[i];
          else {
            fprintf(stderr, "flag 'o' requires an argument\n");
            return 1;
          }
          j = strlen(arg) - 1;

          out = fopen(output, "wb");
          if(!out) {
            fprintf(stderr, "error opening '%s': %s\n", output, strerror(errno));
            return 1;
          }
          break;
        case 'm':
          if(arg[j + 1]) output = &arg[j + 1];
          else if(++i < argc) output = argv[i];
          else {
            fprintf(stderr, "flag 'm' requires an argument\n");
            return 1;
          }
          j = strlen(arg) - 1;

          memsize = atoi(output);
          if(!memsize) {
            fprintf(stderr, "invalid memory size: %s\n", output);
            return 1;
          }
          break;
        case 'i':
          if(arg[j + 1]) output = &arg[j + 1];
          else if(++i < argc) output = argv[i];
          else {
            fprintf(stderr, "flag 'i' requires an argument\n");
            return 1;
          }
          j = strlen(arg) - 1;

          indsize = strtol(output, &end, 10);
          if(*end != '\0' || indsize < 0) {
              fprintf(stderr, "invalid indentation size: %s\n", output);
              return 1;
          }
          break;
        default:
          fprintf(stderr, "unrecognised flag: '%c'\n"
                          "try '-h' for help\n", arg[j]);
          return 1;
      }
    }
  }

  while(i < argc) {
    if(input) {
      fprintf(stderr, "too many input files\n");
      return 1;
    }
    input = argv[i++];
  }

  if(input) {
    in = fopen(input, "rb");
    if(!in) {
      fprintf(stderr, "error opening '%s': %s\n", input, strerror(errno));
      return 1;
    }
  }

  indent = 1;

  switch(target) {
    case TGT_C:
      fprintf(out, "/* GENERATED BY BFC BRAINFUCK COMPILER */\n\n");
      break;
    case TGT_NASM:
      fprintf(out, "; GENERATED BY BFC BRAINFUCK COMPILER\n\n");
      break;
  }

  if(debug) switch(target) {
    case TGT_C:
      fprintf(out, "/* START BFC PROLOGUE */\n");
      break;
    case TGT_NASM:
      fprintf(out, "; START BFC PROLOGUE\n");
      break;
  }

  switch(target) {
    case TGT_C:
      fprintf(out,
        "#include <stdio.h>\n"
        "#include <stdint.h>\n"
        "\n"
        "int main(void) {\n"
        "%*suint8_t bfc_buf[%d] = {0};\n"
        "%*suint8_t *bfc_ptr = bfc_buf;\n"
        "%*sint bfc_ch;\n"
      , indent * indsize, "", memsize, indent * indsize, "", indent * indsize, "");
      break;
    case TGT_NASM:
      fprintf(out,
        "BITS 64\n"
        "global _start\n"
        "\n"
        "section .bss\n"
        "bfc_buf resb %d\n"
        "\n"
        "section .text\n"
        "_start:\n"
        "%*slea r12, [rel bfc_buf]\n"
      , memsize, indent * indsize, "");
      break;
  }

  if(debug) switch(target) {
    case TGT_C:
      fprintf(out, "/* END BFC PROLOGUE */\n");
      break;
    case TGT_NASM:
      fprintf(out, "; END BFC PROLOGUE\n");
      break;
  }

  fputc('\n', out);

  i = 0;
  while((ch = fgetc(in)) != EOF) {
    orig = ch;
    switch(ch) {
      case '+':
      case '-':
        count = ch == '+' ? 1 : -1;
        if(optimise) {
          while((ch = fgetc(in)) != EOF) {
            if(ch == '+') count++;
            else if(ch == '-') count--;
            else {
              ungetc(ch, in);
              break;
            }
          }
        }
        switch(target) {
          case TGT_C:
            if(count == 1)       fprintf(out, "%*s(*bfc_ptr)++;", indent * indsize, "");
            else if(count == -1) fprintf(out, "%*s(*bfc_ptr)--;", indent * indsize, "");
            else if(count > 0)   fprintf(out, "%*s*bfc_ptr += %d;", indent * indsize, "", count);
            else if(count < 0)   fprintf(out, "%*s*bfc_ptr -= %d;", indent * indsize, "", -count);
            break;
          case TGT_NASM:
            if(count == 1)       fprintf(out, "%*sinc byte [r12]", indent * indsize, "");
            else if(count == -1) fprintf(out, "%*sdec byte [r12]", indent * indsize, "");
            else if(count > 0)   fprintf(out, "%*sadd byte [r12], %d", indent * indsize, "", count);
            else if(count < 0)   fprintf(out, "%*ssub byte [r12], %d", indent * indsize, "", -count);
            break;
        }

        if(debug) switch(target) {
          case TGT_C:
            if(optimise) fprintf(out, " /* (%d) %c */", count > 0 ? count : -count, orig);
            else         fprintf(out, " /* %c */", orig);
            break;
          case TGT_NASM:
            if(optimise) fprintf(out, " ; (%d) %c", count > 0 ? count : -count, orig);
            else         fprintf(out, " ; %c", orig);
            break;
        }
        fputc('\n', out);
        break;
      case '>':
      case '<':
        count = ch == '>' ? 1 : -1;
        if(optimise) {
          while((ch = fgetc(in)) != EOF) {
            if(ch == '>') count++;
            else if(ch == '<') count--;
            else {
              ungetc(ch, in);
              break;
            }
          }
        }
        switch(target) {
          case TGT_C:
            if(count == 1)       fprintf(out, "%*sbfc_ptr++;", indent * indsize, "");
            else if(count == -1) fprintf(out, "%*sbfc_ptr--;", indent * indsize, "");
            else if(count > 0)   fprintf(out, "%*sbfc_ptr += %d;", indent * indsize, "", count);
            else if(count < 0)   fprintf(out, "%*sbfc_ptr -= %d;", indent * indsize, "", -count);
            break;
          case TGT_NASM:
            if(count == 1)       fprintf(out, "%*sinc r12", indent * indsize, "");
            else if(count == -1) fprintf(out, "%*sdec r12", indent * indsize, "");
            else if(count > 0)   fprintf(out, "%*sadd r12, %d", indent * indsize, "", count);
            else if(count < 0)   fprintf(out, "%*ssub r12, %d", indent * indsize, "", -count);
            break;
        }

        if(debug) switch(target) {
          case TGT_C:
            if(optimise) fprintf(out, " /* (%d) %c */", count > 0 ? count : -count, orig);
            else         fprintf(out, " /* %c */", orig);
            break;
          case TGT_NASM:
            if(optimise) fprintf(out, " ; (%d) %c", count > 0 ? count : -count, orig);
            else         fprintf(out, " ; %c", orig);
            break;
        }
        fputc('\n', out);
        break;
      case '.':
        switch(target) {
          case TGT_C:
            fprintf(out, "%*sputchar(*bfc_ptr);", indent * indsize, "");
            break;
          case TGT_NASM:
            fprintf(out, "%*smov rax, 1\n"
                         "%*smov rdi, 1\n"
                         "%*smov rsi, r12\n"
                         "%*smov rdx, 1\n"
                         "%*ssyscall",
                         indent * indsize, "",
                         indent * indsize, "",
                         indent * indsize, "",
                         indent * indsize, "",
                         indent * indsize, "");
            break;
        }
        if(debug) switch(target) {
          case TGT_C:
            fprintf(out, " /* . */");
            break;
          case TGT_NASM:
            fprintf(out, " ; .");
            break;
        }
        fputc('\n', out);
        break;
      case ',':
        switch(target) {
          case TGT_C:
            fprintf(out, "%*sif((bfc_ch = getchar()) == EOF) *bfc_ptr = 0;\n"
                         "%*selse *bfc_ptr = bfc_ch;\n", indent * indsize, "", indent * indsize, "");
            break;
          case TGT_NASM:
            fprintf(out, "%*smov byte [r12], 0\n"
                         "%*smov rax, 0\n"
                         "%*smov rdi, 0\n"
                         "%*smov rsi, r12\n"
                         "%*smov rdx, 1\n"
                         "%*ssyscall",
                         indent * indsize, "",
                         indent * indsize, "",
                         indent * indsize, "",
                         indent * indsize, "",
                         indent * indsize, "",
                         indent * indsize, "");

            break;
        }
        if(debug) switch(target) {
          case TGT_C:
            fprintf(out, " /* , */");
            break;
          case TGT_NASM:
            fprintf(out, " ; ,");
            break;
        }
        fputc('\n', out);
        break;
      case '[':
        switch(target) {
          case TGT_C:
            fprintf(out, "%*swhile(*bfc_ptr) {", indent * indsize, "");
            break;
          case TGT_NASM:
            id = loopnext++;
            loopstack[looptop++] = id;
            fprintf(out, "loop%d:\n"
                         "%*scmp byte [r12], 0\n"
                         "%*sje end%d", id, indent * indsize, "", indent * indsize, "", id);
            break;
        }
        if(debug) switch(target) {
          case TGT_C:
            fprintf(out, " /* [ */");
            break;
          case TGT_NASM:
            fprintf(out, " ; [");
            break;
        }
        fputc('\n', out);
        if(target & 1) indent++;
        break;
      case ']':
        if(indent <= 1 && target & 1) {
          fprintf(stderr, "mismatched parenthesis%s\n", debug ? " (close)" : "");
          return 1;
        }
        if(target & 1) indent--;
        switch(target) {
          case TGT_C:
            fprintf(out, "%*s}", indent * indsize, "");
            break;
          case TGT_NASM:
            id = loopstack[--looptop];
            fprintf(out, "%*scmp byte [r12], 0\n"
                         "%*sjne loop%d\n"
                         "end%d:", indent * indsize, "", indent * indsize, "", id, id);
        }
        if(debug) switch(target) {
          case TGT_C:
            fprintf(out, " /* ] */");
            break;
          case TGT_NASM:
            fprintf(out, " ; ]");
            break;
        }
        fputc('\n', out);
        break;
      default:
        break;
    }
    i++;
  }
  if(indent != 1 && target & 1) {
    fprintf(stderr, "mismatched parenthesis%s\n", debug ? " (open)" : "");
    return 1;
  }
  fputc('\n', out);
  if(debug) switch(target) {
    case TGT_C:
      fprintf(out, "/* START BFC EPILOGUE */\n");
      break;
    case TGT_NASM:
      fprintf(out, "; START BFC EPILOGUE\n");
      break;
  }

  switch(target) {
    case TGT_C:
      fprintf(out,
        "%*sreturn 0;\n"
        "}\n"
      , indent * indsize, "");
      break;
    case TGT_NASM:
      fprintf(out,
        "%*smov rax, 60\n"
        "%*smov rdi, 0\n"
        "%*ssyscall\n"
      , indent * indsize, "", indent * indsize, "", indent * indsize, "");
      break;
  }
  if(debug) switch(target) {
    case TGT_C:
      fprintf(out, "/* END BFC EPILOGUE */\n");
      break;
    case TGT_NASM:
      fprintf(out, "; END BFC EPILOGUE\n");
      break;
  }
  if(in != stdin) fclose(in);
  if(out != stdout) fclose(out);
  return 0;
}
