/*
    +-----+
    | BFC |
    +-----+

    Code-formatting Brainfuck compiler and transpiler with codegen support for C and Linux x86_64 NASM
*/

#include <stdio.h>
#include <errno.h>
#include <string.h>
#include <stdbool.h>
#include <stdlib.h>

int main(int argc, char **argv) {
  /* file streams */
  FILE *in = stdin, *out = stdout;
  /* compilation variables */
  int ch, count, indent, orig;
  /* nasm loop stack */
  int loopstack[1024];
  int looptop = 0, loopnext = 0, id;
  /* arg parsing variables */
  int i, j;
  char *arg, *output, *end;
  /* options */
  bool optimise = false, debug = false, nasm = false;
  int memsize = 65536, indsize = 2;
  char *input = NULL;

  for(i = 1; i < argc; i++) {
    arg = argv[i];
    if(strcmp(arg, "--") == 0) {
      i++;
      break;
    }
    if(arg[0] != '-' || arg[1] == '\0') {
      input = arg;
      i++;
      break;
    }
    for(j = 1; arg[j]; j++) {
      switch(arg[j]) {
        case 'h':
          printf("bfc: brainfuck compiler\n\nusage: %s [-h] [-n] [-O] [-d] [-o outfile] [-m memsize] [-i indsize] [--] [infile]\n", argv[0]);
          return 0;
        case 'n':
          nasm = true;
          break;
        case 'O':
          optimise = true;
          break;
        case 'd':
          debug = true;
          break;
        case 'o':
          if(arg[j + 1]) output = &arg[j + 1];
          else if(++i < argc) output = argv[i];
          else {
            fprintf(stderr, "flag 'o' requires an argument\n");
            return 1;
          }
          j = strlen(arg) - 1;

          out = fopen(output, "wb");
          if(!out) {
            fprintf(stderr, "error opening '%s': %s\n", output, strerror(errno));
            return 1;
          }
          break;
        case 'm':
          if(arg[j + 1]) output = &arg[j + 1];
          else if(++i < argc) output = argv[i];
          else {
            fprintf(stderr, "flag 'm' requires an argument\n");
            return 1;
          }
          j = strlen(arg) - 1;

          memsize = atoi(output);
          if(!memsize) {
            fprintf(stderr, "invalid memory size: %s\n", output);
            return 1;
          }
          break;
        case 'i':
          if(arg[j + 1]) output = &arg[j + 1];
          else if(++i < argc) output = argv[i];
          else {
            fprintf(stderr, "flag 'i' requires an argument\n");
            return 1;
          }
          j = strlen(arg) - 1;

          indsize = strtol(output, &end, 10);
          if(*end != '\0' || indsize < 0) {
              fprintf(stderr, "invalid indentation size: %s\n", output);
              return 1;
          }
          break;
      }
    }
  }

  while(i < argc) {
    if(input) {
      fprintf(stderr, "too many input files\n");
      return 1;
    }
    input = argv[i++];
  }

  if(input) {
    in = fopen(input, "rb");
    if(!in) {
      fprintf(stderr, "error opening '%s': %s\n", input, strerror(errno));
      return 1;
    }
  }

  indent = 1;

  fprintf(out, "%s GENERATED BY BFC BRAINFUCK COMPILER%s\n\n", nasm ? ";" : "/*", nasm ? "" : " */");

  if(debug) fprintf(out, "%s START BFC PROLOGUE%s\n", nasm ? ";" : "/*", nasm ? "" : " */");

  if(nasm)
    fprintf(out,
      "global _start\n"
      "\n"
      ".section bss\n"
      "bfc_buf resb %d\n"
      "\n"
      ".section text\n"
      "_start:\n"
      "%*slea r12, [rel bfc_buf]\n"
    , memsize, indent * indsize, "");
  else
    fprintf(out,
      "#include <stdio.h>\n"
      "#include <stdint.h>\n"
      "\n"
      "int main(void) {\n"
      "%*suint8_t bfc_buf[%d] = {0};\n"
      "%*suint8_t *bfc_ptr = bfc_buf;\n"
    , indent * indsize, "", memsize, indent * indsize, "");

  if(debug) fprintf(out, "%s END BFC PROLOGUE%s\n", nasm ? ";" : "/*", nasm ? "" : " */");

  fputc('\n', out);

  i = 0;
  while((ch = fgetc(in)) != EOF) {
    orig = ch;
    switch(ch) {
      case '+':
      case '-':
        count = ch == '+' ? 1 : -1;
        while((ch = fgetc(in)) != EOF) {
          if(ch == '+') count++;
          else if(ch == '-') count--;
          else {
            ungetc(ch, in);
            break;
          }
        }
        if(nasm) {
          if(count == 1)       fprintf(out, "%*sinc byte [r12]", indent * indsize, "");
          else if(count == -1) fprintf(out, "%*sdec byte [r12]", indent * indsize, "");
          else if(count > 0)   fprintf(out, "%*sadd byte [r12], %d", indent * indsize, "", count);
          else if(count < 0)   fprintf(out, "%*ssub byte [r12], %d", indent * indsize, "", -count);
        } else {
          if(count == 1)       fprintf(out, "%*s(*bfc_ptr)++;", indent * indsize, "");
          else if(count == -1) fprintf(out, "%*s(*bfc_ptr)--;", indent * indsize, "");
          else if(count > 0)   fprintf(out, "%*s*bfc_ptr += %d;", indent * indsize, "", count);
          else if(count < 0)   fprintf(out, "%*s*bfc_ptr -= %d;", indent * indsize, "", -count);
        }
        if(debug) {
          if(optimise) fprintf(out, " %s (%d) %c%s", nasm ? ";" : "/*", count > 0 ? count : -count, orig, nasm ? "" : " */");
          else         fprintf(out, " %s %c%s", nasm ? ";" : "/*", orig, nasm ? "" : " */");
        }
        fputc('\n', out);
        break;
      case '>':
      case '<':
        count = ch == '>' ? 1 : -1;
        while((ch = fgetc(in)) != EOF) {
          if(ch == '>') count++;
          else if(ch == '<') count--;
          else {
            ungetc(ch, in);
            break;
          }
        }
        if(nasm) {
          if(count == 1)       fprintf(out, "%*sinc r12", indent * indsize, "");
          else if(count == -1) fprintf(out, "%*sdec r12", indent * indsize, "");
          else if(count > 0)   fprintf(out, "%*sadd r12, %d", indent * indsize, "", count);
          else if(count < 0)   fprintf(out, "%*ssub r12, %d", indent * indsize, "", -count);
        } else {
          if(count == 1)       fprintf(out, "%*sbfc_ptr++;", indent * indsize, "");
          else if(count == -1) fprintf(out, "%*sbfc_ptr--;", indent * indsize, "");
          else if(count > 0)   fprintf(out, "%*sbfc_ptr += %d;", indent * indsize, "", count);
          else if(count < 0)   fprintf(out, "%*sbfc_ptr -= %d;", indent * indsize, "", -count);
        }
        if(debug) {
          if(optimise) fprintf(out, " %s (%d) %c%s", nasm ? ";" : "/*", count > 0 ? count : -count, orig, nasm ? "" : " */");
          else         fprintf(out, " %s %c%s", nasm ? ";" : "/*", orig, nasm ? "" : " */");
        }
        fputc('\n', out);
        break;
      case '.':
        if(nasm) fprintf(out, "%*smov rax, 1\n"
                              "%*smov rdi, 1\n"
                              "%*smov rsi, r12\n"
                              "%*smov rdx, 1\n"
                              "%*ssyscall",
                              indent * indsize, "",
                              indent * indsize, "",
                              indent * indsize, "",
                              indent * indsize, "",
                              indent * indsize, "");
        else fprintf(out, "%*sputchar(*bfc_ptr);", indent * indsize, "");
        if(debug) fprintf(out, " %s .%s", nasm ? ";" : "/*", nasm ? "" : " */");
        fputc('\n', out);
        break;
      case ',':
        if(nasm) fprintf(out, "%*smov rax, 0\n"
                              "%*smov rdi, 0\n"
                              "%*smov rsi, r12\n"
                              "%*smov rdx, 1\n"
                              "%*ssyscall",
                              indent * indsize, "",
                              indent * indsize, "",
                              indent * indsize, "",
                              indent * indsize, "",
                              indent * indsize, "");
        else fprintf(out, "%*s*bfc_ptr = getchar();", indent * indsize, "");
        if(debug) fprintf(out, " %s ,%s", nasm ? ";" : "/*", nasm ? "" : " */");
        fputc('\n', out);
        break;
      case '[':
        if(nasm) {
          id = loopnext++;
          loopstack[looptop++] = id;
          fprintf(out, "loop%d:\n"
                       "%*scmp byte [r12], 0\n"
                       "%*sje end%d", id, indent * indsize, "", indent * indsize, "", id);
        } else fprintf(out, "%*swhile(*bfc_ptr) {", indent * indsize, "");
        if(debug) fprintf(out, " %s [%s", nasm ? ";" : "/*", nasm ? "" : " */");
        fputc('\n', out);
        if(!nasm) indent++;
        break;
      case ']':
        if(indent <= 1) {
          fprintf(stderr, "mismatched parenthesis%s\n", debug ? " (close)" : "");
          return 1;
        }
        if(!nasm) indent--;
        if(nasm) {
          id = loopstack[--looptop];
          fprintf(out, "%*scmp byte [r12], 0\n"
                       "%*sjne loop%d\n"
                       "end%d:", indent * indsize, "", indent * indsize, "", id, id);
        } else fprintf(out, "%*s}", indent * indsize, "");
        if(debug) fprintf(out, " %s ]%s", nasm ? ";" : "/*", nasm ? "" : " */");
        fputc('\n', out);
        break;
      default:
        break;
    }
    i++;
  }
  if(indent != 1) {
    fprintf(stderr, "mismatched parenthesis%s\n", debug ? " (open)" : "");
    return 1;
  }
  fputc('\n', out);
  if(debug) fprintf(out, "%s START BFC EPILOGUE%s\n", nasm ? ";" : "/*", nasm ? "" : " */");
  if(nasm) {
    fprintf(out,
      "%*smov rax, 60\n"
      "%*smov rdi, 0\n"
      "%*ssyscall\n"
    , indent * indsize, "", indent * indsize, "", indent * indsize, "");
  } else {
    fprintf(out,
      "%*sreturn 0;\n"
      "}\n"
    , indent * indsize, "");
  }
  if(debug) fprintf(out, "%s END BFC EPILOGUE %s\n", nasm ? ";" : "/*", nasm ? "" : " */");
  if(in != stdin) fclose(in);
  if(out != stdout) fclose(out);
  return 0;
}
